### ISSUE TITLE
Crear hoja de estilo maestra

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#1]
Crear la hoja de estilos CSS, creando los estilos de todos los componentes de la interfaz.

**Comment by matiasHardCoder** [comment]
Como cada componente usa su propia hoja de estilos (según estructura sugerida por la documentación del framework) esta tarea queda obsoleta. En cambio, se opta por incorporar al proyecto la librería _Material-ui_, la cual tiene los mismos componentes con los cuales se diseñó la maqueta. En este escenario, como el objetivo principal de esta tarea es dar estilos a todos los elementos de la interfaz, se opta por codificar los elementos comunes de la aplicación como el SideBar, el AppBar, las tarjetas, la definición de estilos de las tipografías.
