### ISSUE TITLE
Interfaz de Creación de Módulo

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#2]
Codificar la interfaz de creación de módulo del sistema.

**Comment by matiasHardCoder** [comment]
@Yarixa Se implementan las vistas respectivas y las funcionalidades para el módulo de gestión de módulos bajo arquitectura redux. Se deja abierto éste issue hasta que se integren las funcionalidades con los paths de la api.
