### ISSUE TITLE
Creación de un usuario en la base de datos

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#22]
Implemente la creación de un usuario en la base de datos, recibiendo y almacenando los atributos pertenecientes a un usuario.

**Comment by Haliberd** [comment]
La funcion users.create() dentro de /routes/Users.js permite crear un usuario entregando su nombre, apellido, email y contraseña. Faltan comprobaciones con respecto a este tema y esa es la única razón por la cual no he cerrado este issue.
