### ISSUE TITLE
Edición de usuario de la base de datos

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#23]
Implemente la creación de un usuario en la base de datos, recibiendo y almacenando los atributos pertenecientes a un usuario.

**Comment by Haliberd** [comment]
Se ha realizado una operación similar a esta. users.updatePassword() es una función similar que permite a un usuario el cambiar su contraseña. Por lo tanto, no creo que la función de edición de usuario (excepto por su correo) sea un problema.
