### ISSUE TITLE
Eliminación de un usuario de la base de datos 

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#24]
Implementar la eliminación de un módulo en la base de datos.

**Comment by Haliberd** [comment]
Existe un pequeño error en la descripción. De todas formas, la eliminación de un usuario por sí ya esta completa. La función users.delete() encontrada en Users.js contiene la funcionalidad necesaria para eliminar un usuario, para esto es necesario pasar el email como atributo. Aun así, probablemente esta funcionalidad sea cambiada por "desactivar usuario" para así no tener problemas con la BD.
