### ISSUE TITLE
Consulta a la base de datos de visualización de usuario

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#25]
Implemente la consulta que permita ver usuarios de la base de datos.

**Comment by Haliberd** [comment]
La consulta de visualización esta en proceso de desarrollo, se esta pensando en una acción de tipo get, y estoy viendo tutoriales para realizar dicha acción. Probablemente no estará lista para esta iteración.

**Comment by Haliberd** [comment]
Añadida función de tipo GET llamada readAll(), dicha función devuelve todos los usuarios ingresados en la base de datos. Puede limitarse usando alguna condición, pero esta funcionalidad todavía no ha sido agregada. Probablemente haré otra función para eso.
