### ISSUE TITLE
Integración a SendGrid

### ISSUE THREAD

**Issue by Haliberd** [lgsilvestre/SoftProyectAdmin_G4#27]
Crear un módulo para enviar correos con las nuevas contraseñas usando SendGrid. Esta tarea contempla varios sprints.

**Comment by Haliberd** [comment]
![correo_de_prueba1](https://user-images.githubusercontent.com/22768648/83067684-1a1c6200-a035-11ea-95e4-8a702432b5cb.png)
![correo_de_prueba2](https://user-images.githubusercontent.com/22768648/83067700-21437000-a035-11ea-9f0a-6fecef191cd5.png)

He aquí las imágenes para ver como queda el correo.
En el caso de Gmail, el correo llega a promociones. No se descarta de que pueda llegar a Spam.
En el caso de Outlook, el correo llega a Spam.

Para poder hacer funcionar este módulo es necesario el solicitar la API KEY por Discord.

Cabe destacar de que solo se pueden enviar 100 correos diarios, por lo tanto, recomiendo tener discreción.

**Comment by Haliberd** [comment]
Hasta nuevo aviso, SendGrid se encuentra deshabilitado para cualquier persona que quiera enviar correos.

**Comment by matiasHardCoder** [comment]
Issue cerrado hasta nuevo aviso
