### ISSUE TITLE
Integración Front-Back versión 1.0

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#32]

**Comment by matiasHardCoder** [comment]
Se culmina la sesión de integración obteniendo como resultado la suma de todo nuestro trabajo. Queda pendiente la actualización de los paths del back-end en el front-end y realizar retoques estéticos en orden de obtener la versión 1.0 de la aplicación.  Todo el trabajo realizado en este proceso se realiza en co-autoría con: @jorquera1401 @Haliberd @xPashox @Yarixa @lnguz.
