### ISSUE TITLE
Interfaz y lógica Login

### ISSUE THREAD

**Issue by jorquera1401** [lgsilvestre/SoftProyectAdmin_G4#34]
Esta tarea comprende el desarrollo de la vista login y su respectiva integración con la api.

- [x] Componentes visuales
- [x] Lógica _Redux_
- [x] Integración con _API_

**Comment by matiasHardCoder** [comment]
Me sumo al avance de este issue por esta semana por asuntos de gestión de tiempos, me hago cargo de la codificación de la interfaz y la lógica.

**Comment by matiasHardCoder** [comment]
En el último commit solamente se codifican las vistas, dejo pendiente para próxima iteración la integración con las respectivas funciones del back-end.

**Comment by matiasHardCoder** [comment]
Se cierra este issue por finalización de las tareas  relacionadas con éste. Se implementa el módulo de login con corrección de errores e integración con módulo de sesión.
