### ISSUE TITLE
Interfaz de Eliminación de Módulo

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#4]
Codificar la interfaz de eliminación de Módulos.

**Comment by matiasHardCoder** [comment]
@Yarixa Se implementan las vistas respectivas y las funcionalidades para el módulo de gestión de módulos bajo arquitectura redux. Se deja abierto éste issue hasta que se integren las funcionalidades con los paths de la api.
