### ISSUE TITLE
Interfaz de Visualización de Módulo

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#5]
Codificar la interfaz de Visualización de Módulos.

**Comment by matiasHardCoder** [comment]
Se entiende que éste issue comprende la implementación de la vista del listado de módulos y sus funcionalidades. Se asume que las éstas funcionalidades serán bajo la arquitectura redux. Así, en el commit [32b52d7](https://github.com/lgsilvestre/SoftProyectAdmin_G4/commit/32b52d7325966dffa80146b8381f5e1f2885982c) se hizo una implementación preliminar de la arquitectura con el fin de brindar una funcionalidad que era necesaria y, además, conocer el funcionamiento en detalle de la arquitectura, en orden de poder replicarla en las funcionalidades de la gestión de módulos.

**Comment by matiasHardCoder** [comment]
Se implementan las vistas respectivas y las funcionalidades para el módulo de gestión de módulos bajo arquitectura redux. Se deja abierto éste issue hasta que se integren las funcionalidades con los paths de la api.

**Comment by matiasHardCoder** [comment]
Ya completada la integración con el backend, se cierra este issue.
