### ISSUE TITLE
Creación de Módulo en la base de datos

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#6]
Implementar la creación de un módulo en la base de datos, recibiendo y almacenando los atributos pertenecientes a un módulo.

**Comment by jorquera1401** [comment]
Se implementa la creación de la conexión con el la tabla Subject (Modulo), se configura la conexion con la base de datos.
Se implementa la creación de un módulo.
Falta probar su funcionamiento
