### ISSUE TITLE
Edición de Módulo de la base de datos

### ISSUE THREAD

**Issue by Yarixa** [lgsilvestre/SoftProyectAdmin_G4#7]
Implementar la edición de un módulo en la base de datos, recibiendo y almacenando los atributos a editar pertenecientes al módulo.

**Comment by jorquera1401** [comment]
Se implementa el metodo para la edicion del modulo a traves del  metodo _post_ '/delete', se utiliza como parametro la _id_ del modulo 
_Falta probar su implementacion_
