### ISSUE TITLE
Gestion de Documentos (FRONT)

### ISSUE THREAD

**Issue by jorquera1401** [lgsilvestre/SoftProyectAdmin_G4#77]
Se agrega una prueba preliminar de gestion de documentos con editor de texto enriquecido

**Comment by matiasHardCoder** [comment]
Se culmina esta tarea implementando el routing hacia las vistad de creación para cada documento, dashboard de proyectos y un componente con la versión preliminar del módulo de creación de texto enriquecido. También se creó el servicio a nivel de backend para esta funcionalidad.
